samtools/hts-specs

VCFv4.2.tex
The NA00002 GQ in the VCF line does not match the encoded equivalent.
=> Fix typo in Genotype encoding example

SAMv1.tex
See motivation in #36 and [several samtools#304 comments](https://github.com/samtools/samtools/issues/304#issuecomment-57438913): in short, SAM should be able to represent everything that BAM can represent.
The footnote text at line 860ff originally (see ec8fe9550700fc1d727de52e277faebf4d2e59fc) said
> An integer may be stored [in BAM] as `cCsSiI` depending on the magnitude of the integer. In SAM, all integer types are mapped to `i`.
It was later changed in 598d0141b6cab13afd1f51dc6cf98b815a49827c ("[...] Added BAM tag type "B"; Other format changes and minor clarifications") and ceaff87e7afaef8b754fd6d7ae9354c5a45d2e27 ("Added the B type"; addition of "single") to
> An integer may be stored as one of `cCsSiI` in BAM, representing `int8_t`, `uint8_t`, `int16_t`, `uint16_t`, `int32_t` and …
=> Remove SAM's artificial 'i' optional field range limit

SAMv1.tex
See #52 for motivation.  See also e6ca319516752ecdbc25b5880c41b1a4970dd0ec, prior to which the spec stated
> Bits 0x10 and 0x20 only indicate the strand of the fragment. Unmapped reads may have these two bits set.
In this pull request, _When bit 0x4 is unset, this corresponds to the strand to which the segment has been mapped_ attempts to say the same thing as the previous "strand of the fragment".
Also recommend that unmapped reads be stored as they came off the machine.
=> State that reverse flag is meaningful for unmapped reads

SAMv1.tex
1. Reinstate the previously-specified `@HD-GO` tag.  See #15.  The text in the pre-TeX specification was
> **GO**  Group order (full sorting is not imposed in a group). Valid values: none (default), query, and reference.
It would be possible to require that if both `SO` and `GO` are specified then they must agree with each other (e.g. `SO:queryname GO:query`), but it seems easier to discourage specifying both together.  (Also perhaps we could have a footnote noting that `GO:reference` is fairly pointless!)
2. Add `ONT` (Oxford Nanopore) as a valid value for `@RG-PL`.  See #39.
3. Add new free-form `@RG-PM` tag to allow more details about the platform to be given, e.g., machine models such as 'HiSeq 2500'.  See #16.
These additions mangle the formatting of the header table, but I propose …
=> Collected header additions: HD-GO, RG-PL:ONT, and RG-PM

CRAMv3.tex
See https://sourceforge.net/p/samtools/mailman/message/34293215/ for a
discussion on these.  The first of these is just a bad example which
appears to have been incorrect since version 1.1.  The second is an
error caused during the multi-base sequence and quality features.
They're listed as BA/QS data series but are implemented in both C and
Java as BB/QQ.
Additionally the 'A' "bases and scores" pair is not implemented in
either C nor Java.  I commented this out for now as we haven't found a
reason for it and if anyone else did start using it then it'd break
our implementations.
=> FAO @vadimzalunin: Fixed bad encoding example.  Fixed Feature Codes table.

SAMv1.tex
1. Generalise 0x200 flag bit as _filtered-out bit_, as discussed in #85.
2. Clarify that unspecified FLAG bits are reserved for future use, in response to a [samtools-devel question](http://sourceforge.net/p/samtools/mailman/message/34386981/).  Possibly this would be better added to §**Recommended Practice** rather than in the **FLAG** definition?
3. Change SAM maximum QNAME length to match the BAM limit.
=> Various small SAM spec changes

Makefile, VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex
Please see also the list of open issues here:
https://github.com/samtools/hts-specs/labels/vcf
=> VCFv4.3 - first batch of changes

SAMv1.tex
These are supported in BAM implementations but not permitted in SAM.
Also changed H to require an even number of bytes as this was
(probably) an oversight and is enforced by some implementations
(htsjdk, maybe more).
Fixes #135
=> Changed Z and H aux types to handle zero-length strings.

CRAMv2.1.tex, CRAMv3.tex
Correction for issue #141 and candidate text for a very brief version summary for review by @vadimzalunin.  If you're happy with it Vadim, feel free to merge.   (We can discuss tomorrow if you're at the meeting.)   Maybe the history should be moved to the start, but it's where it is simply because that's where the valid version numbers are enumerated.   I'm happy with it in either place.
Also added a very brief one-line summary of the differences between
version numbers.   Not intended to be exhaustive.  Fixes #141
=> Corrected the CRAM File Definition major/minor version numbers.

SAMv1.tex
This PR adds the AH header tag to @SQ. It indicates whether a reference sequence is an alternate haplotype. Reads mapped to the primary assembly and alternate haplotypes usually receive different treatment in processing. BWA will generate this tag. I am also open to other options.
=> Added the AH header tag to @SQ

VCFv4.3.tex
Subset of changes listed in #123. These are restricted to INFO fields, reformatting their description as a table, so Number and Type can be made explicit.
In some cases, Number and Type were already listed in the field description, in others they can be inferred, and in others they were extracted from the sample at the beginning of the specification document.
Fields with issues:
* MQ: INFO Type not specified. FORMAT Type is Integer, but an RMS should be a Float?
* SB: Number or Type not specified and can't be directly inferred from description
* DB, H2 and rest of flags: Only Number=0 is allowed, but this doesn't work well for multi-allelic variants as discussed in https://github.com/samtools/hts-specs/pull/123#r66714347
=> Table describing INFO reserved fields

VCFv4.3.tex
Subset of changes listed in #123. These are restricted to FORMAT fields, adding a table to the plain-text description, so Number and Type can be made always explicit.
In some cases, Number and Type were already listed in the field description, in others they could be inferred, and in others they were extracted from the sample at the beginning of the specification document.
The tables for INFO and FORMAT have been formatted to have the same column width.
=> Table describing FORMAT reserved fields

htsget.md
This is an update of the htsget error handling with a few changes. The initial draft is really just for discussion, as it seemed more efficient to make the changes and discuss them concretely rather than in issues.
Changes:
1. Removed HTTP 409, 406 and 416 as discussed in #186.
2. Changed the text where it referred to HTTP codes to refer to the specific error 'classes' that we have defined. 
3. Tried to be more RFC2119 about the language used to describe when and what type of errors should be raised.
4. Changed the structure of the JSON error object to remove the embedded "error" field (seems superfluous), and added a table to document the fields more systematically.
5. Added an ``InvalidRange`` error for when start > end. (Superfluous?)
Apologies for rolling so many changes together, but …
=> Make error handling more concrete & remove some HTTP codes.

htsget.md
As discussed in yesterday's conference call, this PR removes the ``referenceMD5`` query parameter. The motivations for this are:
1. It has not been yet been implemented by enough servers, and we would like to hit v 1.0 of the spec soon.
2. It was not very well specified from a client perspective (i.e., should a client expect both referenceName and referenceMD5 to both be supported? Or one or the other? Is one or other considered mandatory for a conforming server?).
3. It is arguably redundant, since actual information discovery is done upstream of htsget where accurate reference sequence specification can be done. The ``referenceName`` part of this protocol can be seen as a local reference ID, and need not have any global interpretation.
=> Remove referenceMD5 query parameter.

MAINTAINERS.md, README.md, index.md
List of maintainers in `MAINTAINERS.md`. Reference to said list in `README.md`, with a gentle reminder to use GitHub in the first place.
=> Added list of specification maintainers

SAMtags.tex
The original intention was E2 as base calls.  See https://sourceforge.net/p/samtools/mailman/message/23947691/.  This looks to just be a typo in the original transcribing from the SAM spec.
=> Fixed the value type for E2 tag.

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex
=> Fix typo in BCF spec, 1 element string is 0x17, not 0x19

SAMv1.tex
Proposed text to implement #100, "suggestion: aliases in `@SQ` section".
Also take the opportunity to pre-emptively restrict the characters allowed in these alternative names.
As noted [in last September's meeting](https://github.com/samtools/hts-specs/issues/100#issuecomment-264209422), restricting the characters allowed in `AN` alternative names could be a first step towards applying the same restriction in `SN` canonical sequence names and finally being able to parse the colon in `chr:beg-end` unambiguously.
There is debate to be had about which punctuation characters to forbid; there are existing points for consideration in #100, #124, and #167.
The primary motivation here is to disallow `:` so `chr:beg-end` region syntax is unambiguous, so we have taken advantage of colon being …
=> Add @SQ-AN alternative reference sequence names

htsget.md
Implements the proposal discussed in #207 to wrap the response data like this:
```
{ "htsget" : { ... } }
```
No version number is included here, but it would be trivial to add, either now or later.
=> Proposed htsget protocol identifier in JSON text

htsget.md
Fix table formatting broken by 5448ce9385f48458ca2f18b4b752025465089db1, in particular the [Error Response JSON fields](http://samtools.github.io/hts-specs/htsget.html#error-response-json-fields) table.
It's recommended to preview changes beforehand, or at least to look at the rebuilt GitHub Pages web site afterwards :smile:
@mlin: I recommend merging this immediately on the basis that it is editorially obvious.
=> Fix htsget table formatting

VCFv4.3.tex
Added further clarification to the description of meta INFO fields. The number of values was described explicitly but not their order.
Fixes #154 .
=> Described order in which meta A/R/G values must be listed

htsget.md
By merging this, we will finalize v1.0.0 of the htsget specification. 
Future work on the spec should be carried out on a separate development branch, until the time comes to tag additional discrete versions.
=> htsget v1.0.0

SAMtags.tex, SAMv1.tex
This commit addresses samtools/hts-specs#40. It added optional tag `CG` and
explained the workaround to store alignments with >65535 CIGAR operations in
BAM files. The proposal is implemented in samtools/htslib#560.
=> Support CIGARs with >65535 operations in BAM files

SAMtags.tex
RFC3986 encoding for "%" is "%25" (rather than "%2C", which encodes ",").
=> Fix RFC3986 encoding for "%"

MAINTAINERS.md
Louis Bergelson (me) is replacing David Roazen as the Broad's VCF maintainer
=> changing VCF maintainer in MAINTAINERS.md

VCFv4.3.tex
SB INFO field defined as Number=4, Type=Integer.
Fixes #189
=> Definition of SB INFO field Number and Type

SAMv1.tex
Still to do.
- We need to explicitly add which SAM header fields we permit use of UTF8.
- CRAM?  It's a binary format so I'm didn't change it as I don't think this applies.
- Wording choices: "encodes" maybe isn't the correct word.  Suggestions?
Fixes #197.
=> Explicitly state character encoding, locale, and RE syntax.

htsget.md
This PR squashes and reorganizes the commits in https://github.com/samtools/hts-specs/pull/233/files
=> htsget VCF support

VCFv4.3.tex
1000G does not match the regular expression for INFO keys but needs to be supported for legacy reasons.
Fixes #164
=> INFO key 1000G is allowed as a special legacy value

SAMtags.tex, SAMv1.tex
Clarified SA tag following discussions on the OA tag PR https://github.com/samtools/hts-specs/pull/193
=> SAM SA tag: make rname and strand requirements explicit.

CRAMv2.1.tex, CRAMv3.tex
It is defined as 'int' in the main table, but section 1.5 lists the encoding type as long.  This is both pointless (the mate's AP field is int, not long) and also not how it is implemented in both htsjdk and htslib.  The origin of this stems all the way back to the CRAM 1.0 word document, but was apparently missed when fixing the spec to match the initial Java implementation.
Many of those inconsistencies were fixed, leading to CRAM v2.0 as the initial joint C/Java definition, but this is sadly something that wasn't spotted at the time.
Java code using \<Integer\>: https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/cram/encoding/reader/AbstractReader.java#L53-L54
C code using E_INT: https://github.com/samtools/htslib/blob/develop/cram/cram_encode.c#L1487-L1489.
=> Bug fix NP encoding type.

SAMtags.tex, SAMv1.tex
PR #227 was merged as dab57f44a4d5358e53d9f75a7d6c6ab2924451b3 on 28 November 2017, but the [discussion about bumping the version number](https://github.com/samtools/hts-specs/pull/227#issuecomment-342091422) to indicate the presence of this feature was never returned to:
> [@jkbonfield]
> I'm tempted however to suggest that we ought to bump the SAM version number, even though this is technically a BAM only change. Why? Because there is no BAM version number other than the sledgehammer complete format change and there is the risk that this BAM only change will leak into SAM anyway, hence having a fixed version where we know it can occur (or vice versa, where we know it cannot) acts in a similar way to CG header tag, but more useful IMO. Plus, like it or not, the BAM and SAM formats have …
=> Bump version to VN:1.6 due to long CIGAR strings

VCFv4.3.tex
The end of line formatting is inconsistent across the specification document. Some paragraphs are split in multiple lines, whereas others are written in a single line.
This makes a bit too difficult to review some changes where not only the content is modified, but also the line splits. This PR makes converts all the paragraphs into a single line, so any future changes affect only the content.
=> End of line formatting

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex
fixes #264 
Also took the opportunity to unify the way longish hex data is displayed in that table. splitting the data into nibbles and dropping the `0x` except in the very first nibble.
=> Fixing typos in BCF genotype example table

MAINTAINERS.md, README.md, index.md, pub/refget-openapi.yaml, refget.md
Adding the version 0.2 RR API specification. This spec defines how to query for a sequence by a checksum (`/sequence/:id`), get information about that checksum (`/sequence/:id/metadata`) and information about the capabilities service provides (`/sequence/service-info`).
This service is backwards compatible with the cram reference registry and can be used by CRAM and htslib without modification to either spec.
=> Reference Retrieval API Specification Merge

pub/refget-openapi.yaml
service-info endpoint
------------------------
Nested under /sequence in the 0.2 specs.
https://github.com/samtools/hts-specs/blob/master/refget.md
Method: Fetch information on the service
GET /sequence/service-info
metadata endpoint
------------------------
Wrapped within "metadata" object in the 0.2 specs.
=> Nest service-info under "sequence" and metadata endpoint parameters under "metadata" in refget-openapi.yaml.

pub/refget-openapi.yaml
Suggestion to add 206, 303, 501 return codes for /sequence/{id} defined in the specs.
=> Add 206, 303, 501 return codes for /sequence/{id} in refget-openapi.yaml..

refget.md
See issue #329.
The specification currently states there are two checksum identifiers available of different length. Length should be used to detect which one has been given. If we need to adopt other checksums then the spec will evolve to include other methods to identify the checksum used.
=> Clarification of checksum ID identification

pub/refget-openapi.yaml
PR #331 noted that the text for `Range` in the YAML file was inconsistent with that in the specification.
While it was a Google Docs document, the specification was corrected to reflect that HTTP Range byte ranges are zero-based fully-inclusive. Update the OpenAPI description correspondingly.
Also fix typos.
=> Fix refget-openapi.yaml's Range header description

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex
Many tools assume that there are no duplicate samples IDs in a VCF header line, because otherwise they can't refer to those samples by name, only by column number. This PR explicitly forbids duplicates in all versions of the specification.
Closes #323
=> Duplicate sample IDs not allowed in header line

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex
fixing a typo in the vcf specs
Pegigree -> Pedigree
=> fixing typo in vcf specs

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex
Issue #263 pointed out that the example structural variant VCF includes a GQ field which is typed as a Float.
It's defined elsewhere as an Integer.
This fixes it in the 4.1 -> 4.3 documents.
It also updates the example vcf header version number to match the spec version it's an example for.
Fixes #263
=> Fix type of GQ in example

refget.md
- Accept-Ranges should not be set to None when ?start/end are suppied, "none" implies to clients the server does not support Range requests for all future requests, which is incorrect
=> Correction based on the Sept 18th refget call:

_config.yml, refget.md
During refget's PRC, the reviewers suggested adding a table of contents to the specification. Kramdown can support this via the `{:toc}` tag. Anything that should not be included in the TOC is tagged with `{:.no_toc}`.
The config is setup to build the TOC for all `h1`/`h2`/`h3` tags, which on first inspection looks sufficient.
Because both refget and htsget specifications are written in Markdown it made sense to apply this to both documents.
=> Support table of contents in refget and htsget. See issue #341.

refget.md
See #329
We have removed the reference to aliases. Instead we have formalised alternative checksum support. Alternative checksums must not clash with any other identifier space.
=> Clarify alias usage

VCFv4.3.tex
It got lost in a formatting commit. Fixes #347
=> BND restored as a valid SVTYPE

CRAMv3.tex, algorithmicx.sty, algpseudocode.sty
This is a good thrash at the CRAM spec, fixes #353 and also takes a good stab at making the data series decode order explicit rather than guesswork.  (The tables were almost correct already, but it was never explicitly mentioned.)
It's now using algorithmicx.sty.  I could use use algorithm.sty for slightly better formatting, but it's GPL and for want of a single extra line of formatting I couldn't be bothered to figure out what that means to a text document! (TeX of course is actually a language, but what is the "program" here?)
=> CRAM spec updates; large!

VCFv4.3.tex
Mention that these conventions apply to *some* tag names where L/P/Q acts as a name suffix — for others, like DP, the L/P/Q is just part of the name. Replaces and closes #261.
Fix quote marks and maths formatting. Remove Q's superfluous “which is” to make the text fit better.
=> Add note about tag naming conventions (addresses "Inconsistent use of P suffix" issue)

SAMv1.tex
The suggestion here is to disallow `\ , "'`` () <> [] {}`, i.e., backslashes, commas, various quote marks, and various brackets. Hopefully this is consistent with the statistics listed in #291. Additional counts for some of these characters would be useful  — see https://github.com/samtools/hts-specs/pull/333#issuecomment-422778596 below.
The existing spec uses regular expressions containing ASCII ranges, which is fairly opaque. This PR lists the punctuation characters explicitly and then invents some extra character class notation to refer to the set of allowed characters succinctly and hopefully clearly:
=> Disallow commas and other punctuation in RNAME etc

CRAMv2.1.tex, CRAMv3.tex
By adding `\renewcommand{\ULthickness}{4pt}` and eyeballing the resulting thick bars, verified that the `ulem` package was acting on the `\emph{…}` text (making it underlined rather than italics) and no other text in the two CRAM specs.
Removed `\usepackage{ulem}`. Changed the Hsi-Yang Fritz, et al. reference to a full citation footnote. Changed section references to bold or cross-references, and left other underlined text (which are all introductions/definitions of terms) to revert to italics. (Details in commit message.)
Also a second commit for your consideration, tidying up the formatting of the arithmetic in the _Choosing the container size_ appendix.
@jkbonfield et al: hopefully this is trivial enough to just merge :smile:
=> Avoid \usepackage{ulem} [trivial]

htsget.md
I finally figured out how to get markdown nested inside an HTML \<table\> into a common subset of kramdown and GitHub-flavoured markdown, so that the _italics_ and `code` etc appear as such (rather than as raw markup) in the rest of the tables when viewing _htsget.md_ within the GitHub repository web view.
@mlin: This has no text changes (and I've verified that it makes no difference to how [htsget.html](http://samtools.github.io/hts-specs/htsget.html) is displayed), so IMHO as editor you should feel free to check it over and merge this without conversation or delay.
=> Improve htsget table contents formatting when displayed on GitHub [trivial]

SAMtags.tex, SAMv1.tex
Adds a clear statement that in SAM, mapped reads are represented on the forward genomic strand. Fixes #368 by resurrecting and updating the old text from the original Pages SAM spec.
Spell out the implications of this for the Bit 0x10 text too, i.e., unset=forward, set=reverse.
And minor fixups: strand nomenclature is forward/reverse rather than positive/negative; <strike>formatting and wordsmithing in the first half of the paragraph (i.e., before the table)</strike>.
=> Add note that SAM alignments are always represented on the forward strand

SAMv1.tex
As @yfarjoun noted in https://github.com/samtools/hts-specs/pull/371#discussion_r251888356 the original Heng paragraph here could benefit from a little attention.
This mentions TAB-separation here, similarly to the header section; hopefully clarifies the unavailable-information placeholders values text; and reformats slightly.
Hopefully trivial enough to just merge fairly quickly…
=> Improve the paragraph introducing alignment records

MAINTAINERS.md
* Vadim has effectively retired as CRAM maintainer.  This would
officially replace him with Chris Norman as discussed during our last
meeting.
=> Replace Vadim with Chris Norman as CRAM maintainer

CRAMv3.tex
Update the DecodePositions pseudocode to match htslib/htsjdk behavior: the state of Last Position is initialized with the Slice's Alignment Start, and therefore the Alignment Delta for the first record in a Slice is 0.
=> CRAM: The first record in a slice should have alignment-delta = 0

.circleci/Dockerfile, .circleci/README.md, .circleci/config.yml, .circleci/pdf_comment.js, .gitignore, MAINTAINERS.md, Makefile, _config.yml
This PR adds a continuous integration option that creates the PDFs and serves them up for perusal. 
This informs circle-ci to make all the pdfs and publish them to an accessible location.
See https://circleci.com/gh/samtools/hts-specs for build information.
=> Add Continuous integration to automatically generate PDF and diff-pdfs using circleCI

CRAMv3.tex
- Consistency of s vs sym between ReadFrequences0 and ReadFrequencies1
- Added missing calls to ReadFrequencies0 and ReadFrequencies1
- ReadFrequencies1 now updates F_{sym} and not F_{i}.
- Added missing i++ in RansDecode1.
This pseudocode has been validated using a basic JavaScript
implementation at https://github.com/jkbonfield/hts-specs/tree/cram_reference/cram_reference
=> Fix rANS pseudocode.

pub/refget-openapi.yaml
Corrects three issues:
1. Missing quote in `service-info` path led to unparsable yaml
1. Metadata component `required` block was outdented one level, causing it to not apply to the metadata properties
1. The schema disagreed with the spec in a metadata attribute. It used `circular_locations`, whereas the spec uses `circular_supported`
Also, I changed the servers block to remove details for a particular implementation.
=> Fixes refget-openapi.yaml

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex
Avoid end-of-sentence spacing after i.e. / e.g. / cf. Where i.e. or e.g. delimits separate clauses, use a comma to set it off, e.g., as the previous comma does in this sentence.
Previously (PR #391) I did this only in VCFv4.3 (and neglected `cf.`). This extends this minor improvement to the other two documents.
No changes to the format or descriptions, so this should be straightforward to review and merge.
=> Trivial VCF formatting improvements

MAINTAINERS.md
Presently I'm the only officially listed maintainer of the htsget spec, which may create bottlenecks when I have limited availability. @jeromekelleher and @jmarshall are nominated here. This was aired on the mailing list a couple of weeks ago with only supportive comments to date.
=> nominate @jeromekelleher and @jmarshall as additional htsget maintainers

CRAMv3.tex
Resolves the remaining piece of #370
=> Slice and Container ref seq IDs must match

CRAMv3.tex
Based on the discussion in https://github.com/samtools/hts-specs/issues/408. @jkbonfield I left the section on substitution frequency sorting in, since it motivates the need for the substitution matrix (otherwise the codes could just be fixed). See what you think.
=> Update CRAM spec section on substitution matrix and codes.

VCFv4.3.tex
INFO/END (when present) determines (together with the CHROM and POS fields) the interval that the variant is located in. This is used when indexing VCF/BCF files, as can be gleaned from §6.3.1's description of BCF's rlen field.
In particular, INFO/END must be on the same chromosome as CHROM and come after POS, otherwise .csi/.tbi indexing will not work. This is implied by the existing description of `rlen`:
> Length of the record as projected onto the reference sequence. Must be the length of the REF allele or the declared length of a symbolic allele respecting the END attribute
but that is hardly obvious, and people looking up INFO/END are unlikely to read it anyway — as it's in the BCF part of the spec.
There has been some discussion of this on PR #266 (starting at …
=> Clarify the meaning of INFO/END

VCFv4.3.tex
The VCF v4.3 spec currently says of Float fields that they are:
> 32-bit, formatted to match the regular expression `^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$`, `NaN`, or `+/-Inf`.
It is not explicit whether `NaN` and `Inf` are intended to be case sensitive, but as they are adjacent to a regexp saying `…[eE]…` the reader's best guess is probably that they are indeed intended to specify that exact capitalisation.
C's `printf` outputs `+`/`-`/no sign as appropriate, followed by `nan` and `inf`/`infinity` (with `%f` etc) or `NAN` and `INF`/`INFINITY` (with `%F` etc); there is no programmer control over whether infinity is 3 or 8 letters, but current glibc and BSD libc output it as 3 letters. Its `scanf` and `strtod` accept all of those completely case-insensitively.
Java's …
=> Allow C and Java native text spellings of NaN and infinities

VCFv4.3.tex
* Adding <NON_REF> to the spec and recommending its use over the <*> allele which is easily confused with *.
* closes https://github.com/samtools/hts-specs/issues/352
=> Suggesting <NON_REF> as the unspecified alt allele

MAINTAINERS.md
Some text that spells out our de facto policy around how to merge PRs (AIUI at least). Mostly our PRs are a single commit that gets modified by a stream of meaningless “fix typo” and “respond to review” commits, so in the usual case that should all be squashed into one commit when the PR is merged.
However there are occasional cases of PRs that tell a story or otherwise have distinct non-trivial commits, so spell out that other treatment for such cases is appropriate.
The **hts-specs** repository currently has all three GitHub UI merge strategies (merge commit; squash; rebase) switched on. It doesn't seem to be possible to change the default; I think it defaults to whatever was selected previously (in the repo / by you / both). We could switch off some of the strategies (i.e. merge …
=> [Meta] Codify the existing policy of generally squashing PRs

CRAMv3.tex
This means AP_delta can become negative.  I have validated this
decodes fine in both htsjdk and htslib.  This is because AP is ITF8
and hence signed, like all other integers, so it would need explicit
code to forbid this (which obviously isn't in the implementations).
Hence the limitation is primarily one of an over-zealous specification.
The impact of this is for position-sorted multi-ref slices AP can
legally be stored efficiently.
Also clarified fields in the container compression header when in
multi-ref mode.
Fixes #431
=> Permit AP_Delta in multi-ref slices

CRAMv3.tex
Minor clarification of how "external"is used (the smallest change I could make to satisfy https://github.com/samtools/hts-specs/issues/426).
=> Distinguish between CRAM external encodings and EXTERNAL proper.

MAINTAINERS.md, Makefile, README.md, crypt4gh.tex, index.md
crypt4gh.tex describes a format for encrypted files which allows for both streaming and random access.
It currently has 'preliminary' stamped across it.  This is because it may still be necessary to make breaking changes following security reviews etc.  Be warned!
=> Adds crypt4gh (GA4GH encrypted file format proposal)

CRAMv3.tex
Fixes #120
I decided after consideration that SM and TD should be mandatory.  TD because TL data series is mandatory so we always look up in TD even when no tags are prevent, so we'd have to specify that blank TD as the default.  SM likewise; it's easier to make it mandatory than to specify the default value.
In both cases there appears to be no way in existing code to create CRAMs that does not add these fields.
=> Specify defaults to booleans in CRAM preservation map

.circleci/Dockerfile, .circleci/config.yml, Makefile
fixed the build so that difflatex uses  `--only-changes` (need a gs…… upgrade as well)
This fixes the the creation of the difflatex pdfs for long tables
=> Fixed the circle-ci build so it works on longtable

SAMv1.tex
This is to support annotating reference sequences as circular, for example for bacterial organisms or the human mitochondrial chromosome.
This is my attempt to keep the momentum for issue https://github.com/samtools/hts-specs/issues/403 going.
@jmarshall @yfarjoun
=> Representation of cross-join mappings on circular reference sequences

CRAMv3.tex
Fixes #453 (mostly).
It doesn't cover the nuances I want for CRAM 4.0, but that will be a separate
commit.  It also glosses over the difference between embedded references and
external references.  We not currently state whether they must be identical
and this is a difference in the htslib and htsjdk implementations so it is
left undecided for now.
=> CRAM: Clarify NM and MD creation

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex
Unlike for the other headers, the section on `##ALT` does not show the `Description` field as having double quotes around it.
However §1.4.2 (Information field format) says Description must be surrounded by double-quotes and this can be construed as applying to Descriptions in all headers, all the other headers show it, all the examples of `##ALT` in the specification have double quotes, and tools such as bcftools and GATK use double quotes in the `##ALT` fields they output. So this is presumably just an omission in the spec.
Hat tip @lltw; see pysam-developers/pysam#881.
=> Show double quotes around ##ALT Description

SAMv1.tex
Quick first draft.  WIP as I need to head off and wanted something in before the file formats meeting. :-)
Replaces #23 and #27 
The observation is that these issues have been around pretty much forever.  They are still hanging around because this is a **hard problem**.  The basic problem is that the specification changed from 5' to 5' to leftmost to rightmost, but most software implementations did not.  New software however adhered to the new spec, meaning we ended up with both definitions in use.  This PR is simply an acceptance that the horse has bolted and to embrace the diversity instead of pretending we can fix it.
Right now it's definitely the case that the dominant use is still 5' to 5'.  We could bless this as the preferred solution, but I haven't yet done this.  Right now I just …
=> Acknowledge the TLEN dichotomy.

htsget.md
The specification text is the original document, while the OpenAPI description is a later simplified contribution from a third party. If there are discrepancies between the two, then it is the OpenAPI description that is incorrect and needs clarifying.
=> Proposal: Clarify that the htsget specification text takes precedence over OpenAPI

SAMtags.tex
TS means: "Strand of the transcript the query sequence represents. Valid values: '+', '-' or '.' (for unknown)." See also #276.
=> added the TS tag for "transcript strand"

refget.md
If there is divergence between refget's text and the OpenAPI, the text is definitive. This is a copy of #472
=> Refget spec text takes precedence over OpenAPI.

SAMv1.tex
Clarify the current rules: having an `@HD` line in your SAM headers is optional, but when present it must come first.
I might have just pushed this to **master**, but presenting this as a PR to give @jkbonfield and @yfarjoun a chance to vet the description of `@HD` as _File-level metadata_ (rather than the current meaninglessly-generic _The header line_!).
Okay to merge? I'd hope we can turn this one around in a day :smile:
=> Clarify the existing rules for the `@HD` header

VCFv4.3.tex, VCFv4.4.tex
* The PP tag is to GP as PL is to GL
* It seems like we should have added PP when we changed the definition of GP to float.
* Reworded slightly because a local reviewer read the term 'precisely as' as a comment on the precision of representation and not as a description of how the field was defined.
* This came up as part of trying to understand https://github.com/samtools/hts-specs/issues/260.  GATK switched from using GP to PP at that time and it seems like an oversight to not add the tag to the spec.
=> Adding PP tag to vcf 4.3 spec.

SAMv1.tex
in the @RG SAM header line.
fixes #178
=> Added BGISEQ as legal value for the PL tag

SAMv1.tex
Revisit PR #460 (see conversation there), adding notes in the existing _Value_ table columns indicating length/count fields whose maximum values are still (well) within the `int32_t` range convenient for e.g. Java arrays. This clarifies that, while the fields are naturally described as `uint32_t`, they are not required to be implemented using such a type if that is inconvenient in your implementation language.
OTOH this PR explicitly raises the `l_text` limit from 2GiB to 4GiB:
* HTSlib already handles 4GiB of BAM header text.
* HTSJDK represents SAM/BAM/etc headers as a collection of separate headers so no representation change is needed to deal with this `l_text` range increase. However _BAMFileReader/Writer.java_'s `readHeader()` and `writeHeader()`  currently operate on the full …
=> Change BAM and BAI length/count fields to uint32_t (PR#460 alternative)

VCFv4.3.tex, VCFv4.4.tex
This change is my interpretation of @pd3 comment at https://github.com/samtools/hts-specs/issues/229#issuecomment-316908769
I did this change only for FORMAT because if an INFO field is missing, you can just not write it. In FORMAT you are forced to write it unless it's the last field.
=> missing FORMAT lists can be . or .,.,. (closes #229)

SAMtags.tex
Fixes #485 — see that issue for much background discussion.
The behaviour described for the more exotic CIGAR operators is derived from that of the `samtools calmd` command and (equivalently) the MD computation in HTSlib's _cram_encode.c_.
This documents the status quo, which requires a `0` between otherwise adjacent mismatch and/or deleted bases.
There would be something to be said for relaxing this and I toyed with adding a footnote along the lines of
> It would be possible to consult the CIGAR string to glean the length of deletions and not need zeros. Reader may wish to do this to additionally accept abbreviated MD strings; writers should output the zeros.
However as discussed on the associated issue, rather than doing that it might be better to revisit the whole question and invent a …
=> Add MD string definition clarifying how MD is constructed

htsget.md
In the spec's front matter, update a mention of JSON format compatibility to refer to OpenAPI Schemas instead of protobuf3.
This edit isn't meant to change the spec materially; merely to modernize this reference in view of the adoption of OpenAPI in numerous GA4GH spec efforts.
=> htsget: refer JSON compatibility to OpenAPI instead of protobuf3

VCFv4.3.tex, VCFv4.4.tex
This PR aims to clarify some points discussed in #437 :
- `*` is a complete allele. It must not be mixed with other ACTG bases.
- Genotypes are meant to be deltas: changes from the reference sequence. Thus, a sample may have a genotype 0 that contradicts another record. Genotype 0 means "no change unless other records say so".
This approach is controversial as can be seen in the issue, but the disadvantages look less important than the following points:
- The notation with base-`*` is more explicit and sometimes clearer but imposes a record interdependency that is not really aligned with VCF in terms of record filtering or VCF merging.
- Following on this independence of records, the genotype 0 has been historically understood by a big part of the community and tools as "this record …
=> VCF: Clarify * as overlapping allele, not overlapping base #437

VCFv4.3.tex, VCFv4.4.tex
This is the best wording I could think of, and still not great. closes #252.
On a more general topic (regarding the PR migration to 4.4), the next commands are simple and worked for me to copy the changes in the last commit from VCFv4.3.tex to VCFv4.4.tex:
```
git diff HEAD^ -- VCFv4.3.tex > my_patch
patch -p1 VCFv4.4.tex  my_patch
```
=> Clarify percent encoding

MAINTAINERS.md
Jerome is no longer an htsget specification maintainer, as discussed during previous htsget meetings.
=> Jerome Kelleher is no longer an htsget maintainer

CSIv1.tex, SAMv1.tex
Ever since the metadata pseudo-bins were added to the spec in #2, their virtual file offset entries have been misdescribed as locating the **placed unmapped reads** (which are not contiguous but spread throughout the reads on the chromosome), contrary to how they are computed by both HTSlib and HTSJDK and to Heng Li's original [description on the samtools-devel mailing list](https://sourceforge.net/p/samtools/mailman/message/25690499/):
> […] each chr has a bin 37450 which currently has two records […]
> The first record keeps the start and end file offset of the entire chr (chunk_beg[0]=chr_start_off, chunk_end[0]=chr_end_off).
Fixes #498 — see additional background there.
Also mention in _CSIv1.tex_ that metadata pseudo-bins appear in CSI too, with the same contents as BAI, and …
=> Fix the description of BAI metadata pseudo-bin file offsets

CRAMv2.1.tex, CRAMv3.tex
The pseudocode in CRAMv3.tex was already correct.
This flaw appears to date all the way back to the initial CRAM1.0 pdf document:
https://www.ebi.ac.uk/sites/ebi.ac.uk/files/groups/ena/documents/cram_format_1.0.1.pdf
Implementation-wise, the initial commit for the CRAMtools Java implementation of CRAM (enasequence/cramtools@6576802) had (Oct 28 2012):
```
public byte getMateFlags() {
if (mateFlags == null) {
byte b = 0;
b |= mateMapped ? 1 : 0;
b <<= 1;
b |= mateNegativeStrand ? 1 : 0;
mateFlags = new Byte(b);
}
return mateFlags;
}
```
7 days later, commit enasequence/cramtools@f0cf055 changed that with:
```
public byte getMateFlags() {
if (mateFlags == null) {
byte b = 0;
-                       b |= mateMapped ? 1 : 0;
+                       b |= mateUmapped ? 1 : 0;
b <<= 1;
b |= …
```
=> Correct CRAM MF bit 2: it means unmapped, not mapped.

pub/htsget-openapi.yaml
@mlin @jmarshall @brainstorm @daviesrob 
Partial solution to fixing OpenAPI repetition. ( issue #489 )
1. Responses
Added a generic `Error` Schema, and an Error schema for each error code outlined in the htsget specification text. These error 'subclasses' inherit from the base `Error` schema through the `allOf` property. These errors are then grouped in `#/components/responses` according to their error code, which are referenced in each API route.
Important to Note: The master branch OpenAPI spec currently has a **misalignment** with the spec markdown, as the OpenAPI error code responses do not prescribe a JSON response with `error` and `message` properties nested under `htsget`. This PR aims to correct this by defining the Error object.
2. Parameters
`class`, `referenceName`, `start`, …
=> fix htsget OpenAPI repetition

SAMv1.tex
Like placed unmapped reads, "mapped" reads with POS set but with unorthodox CIGARs that consume no reference bases would naturally span 0 bases on the reference. We artificially consider unmapped reads to have length 1 for BIN calculation and indexing purposes, so do the same thing for these zero-consumption reads.
See samtools/samtools#1240 and PR samtools/htslib#1063 for context. These are unorthodox alignments used to represent something other than mapping to a reference (if a mapping matches no reference bases at all, on what basis was POS chosen rather than flagging the record as unmapped?), so this change does not affect typical mapped data.
However even when data doesn't particularly mean anything in an alignment context, there's nothing stopping it appearing in a BAM file and it's …
=> Compute BIN for zero-consumption CIGARs as for unmapped reads

VCFv4.1.tex, VCFv4.2.tex
These older specifications currently have no mention of the later VCF specification that supersedes them. This adds such a note on the title page.
The October 2015 date comes from c8194c65a10b9487ab5b65be0ec75a6f11b3005b.
=> Add subtitles noting VCF v4.1 & v4.2 have been superseded by a later version

htsget.md, pub/htsget-openapi.yaml
addition of `/service-info` endpoint to htsget OpenAPI specifcation
=> added /service-info endpoint to htsget openapi specification

SAMv1.tex
Imagine the following scenario:
R1 and R2 form a proper pair in chromosome 1.  I refer to them as R1(p) and R2(p) sometimes before.  R2 also has a secondary alignment in another chromosome, sometimes referred to as R2(s).
The definitions from the spec as it currently stands:
> \item[Multiple mapping]
The correct placement of a read may be ambiguous, e.g., due to repeats.  In
this case, there may be multiple read alignments for the same read.  One of
these alignments is considered primary.  All the other alignments have the
secondary alignment flag set in the SAM records that represent them.  All the
>   \item For each read/contig in a SAM file, it is required that one and only
one line associated with the read satisfies \mbox{`{\sf FLAG} {\tt \& 0x900
== 0}'}. This line is called the …
=> SAM: explicitly limit the TLEN field to the "primary alignment".

SAMv1.tex, test/sam/failed/hdr.SQ14.sam
As mentioned in passing on samtools/htslib#1256, the spec currently doesn't mention that within a single header line, the field tags must all be distinct. HTSJDK has disallowed duplicate header line fields with different values for over a decade, so clarifying this should-be-obvious point shouldn't cause any significant problems.
Also clarify that ordering is insignificant for both header fields and alignment optional fields, which fixes #571.
=> Specify that SAM header field tags must be unique and field ordering is immaterial

htsget.md
...and may in fact need to do so in order to produce a format-valid response. Per discussion #514
=> htsget field filtering: explicate that servers may return a superset of requested fields

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex, VCFv4.4.draft.tex
PR #413 both fixed some typographical errors in `##PEDIGREE` examples and added a new section describing previously undescribed `##PEDIGREE` usage. It has been bogged down for two years as the details of the latter were debated for a while and then ignored.
This PR pulls out the first commit of that, which fixes obvious typographical errors (or possibly transcription errors from when the original g1k wiki VCF text was converted to LaTeX) in the `##PEDIGREE` examples in one section of each spec, and updates it to also fix the errors duplicated into _VCFv4.4.draft.tex_.
This PR simply fixes existing typographical errors in the VCF specs and should be able to be merged without undue delay.
=> Fix `##PEDIGREE` example typographical errors

htsget.md
Some very minor wording improvements noticed while reading through the document:
* Ensure "Protocol essentials" introduction is true for both GET and POST requests.
* Reword POST response sentence to reflect the text reorganisation with the ticket described in a shared later section.
* Fix typo.
* Incidentally caught by checking spelling: capitalise JavaScript etc and format function names.
As this is very minor editorial, I will merge this in a week if there are no concerns expressed, or @mlin should feel free to merge it sooner if he approves these changes as is.
=> Minor rewording to further incorporate POST requests

README.md, index.md
- GA4GH now gets a mention in the introduction.  This links over to the main site as well as the github ga4gh wiki as this has much more information on how we work, minutes, and other LSG projects not in this repository (RNAget).  I am aware the GA4GH web site may get revamped at some point, but we can update again if/when this happens.
- A contributors section has been added at the end.  This is "thin", but it's a start.  I encourage each specification maintainer to look to adding contributors sections to their relevant specs if not already done.
=> Expand introduction to README.

htsget.md
We've gradually added to htsget and not really realised that actually time has passed and we now have a number of previous published htsget protocol versions…
This PR adds an appendix listing the significant functionality introduced and changes made in each published version of the htsget protocol. Fixes #585.
~~It's a bit unfortunate that the “Possible future enhancements” section comes after this version history, but it needs to because the footnotes in “Existing clarification suggestions” are stuck at the end of the document in the web-rendered version. I seem to recall we've discussed creating issues to track each of these enhancement suggestions and removing these sections, which I think we should probably do while considering the text of this PR.~~ [Now done, in …
=> Add htsget protocol version history appendix

BEDv1.tex, MAINTAINERS.md, Makefile, README.md, index.md
Add a Browser Extensible Data (BED) specification.
- [BEDv1.pdf](https://github.com/michaelmhoffman/hts-specs/releases/download/20210923/BEDv1.pdf) draft 2021-09-23 revision 2481c79
- ~[BEDv1.pdf](https://github.com/michaelmhoffman/hts-specs/releases/download/20210831/BEDv1.pdf) draft 2021-08-31 revision 2a5cd5d~
- ~[BEDv1.pdf](https://github.com/michaelmhoffman/hts-specs/releases/download/20210830/BEDv1.pdf) draft 2021-08-30 revision af943fe~
- ~[BEDv1.pdf](https://github.com/michaelmhoffman/hts-specs/releases/download/20210628/BEDv1.pdf) draft 2021-06-28 revision 1caa7c6~
=> Add BEDv1 specification

VCFv4.4.draft.tex
SVTYPE is redundant with with ALT.
This PR deprecates SVTYPE for VCFv4.4.
The field would have to have been redefined as TYPE=A anyway, and 4.4 is our best chance of cleaning up SV handling.
=> Deprecate SVTYPE

VCFv4.4.draft.tex
This PR adds an `EVENTTYPE` field allowing multiple SV records to be grouped together and collectively classified as an event.
This allows for explicit separation of SV breakpoint and CN detection, and genomic rearrangement event classification. The specs currently lack a distinction between detection and classification.
=> EVENT/EVENTTYPE for SV classification

.circleci/pdf_comment.js
This is just a note for the hts-specs-bot PDF links to give notice to their expiring. Just an add-on to #555  to let users/browsers of the PRs that the link is expected to expire
=> Add note about link expiry for pdf_comment

htsget.md
This PR adds notes as suggested in https://github.com/samtools/hts-specs/issues/578#issuecomment-875619649.
Note that the underlying data stream (i.e., file!) **should** contain these headers, and that the response will be a ticket representing headers in the requested or default format (not simply textual SAM/VCF).
These notes aim to
1. Clarify to authors of clients that the response is in `format` not simply textual SAM;
2. Jog readers' memory about `##contig` headers providing this information in VCF;
3. Strongly hint to the operators of htsget servers that the variant data streams presented by their services ought to include `##contig` headers.
=> Add htsget header request note re `@SQ`/`##contig` headers

pub/refget-openapi.yaml, refget.md
Reducing the requirements around content type responses for plain text as previously discussed in refget calls
=> Bump to 1.0.1

MAINTAINERS.md
As discussed at last month's meeting, this PR updates _MAINTAINERS.md_ to reflect changes in active personnel:
* Yossi (SAM) and Petr (VCF) are no longer active maintainers;
* Chris's (CRAM) and Kirill's (VCF) ongoing status and availability are open questions, and they might be added to this PR or a followup.
In conjunction with bringing the listed active maintainers up to date, we will review the membership of “Specification authors”, the samtools GH org team that provides write access to hts-specs:
* Yossi and Petr will be removed when this PR is merged;
* @jmthibault79 is a member of the team, IIRC so that there would be an additional person available to push CRAM updates. Is this still applicable?
* It appears that the crypt4gh maintainers (@AlexanderSenf and @daviesrob) were never …
=> File formats maintainership updates

CRAMv3.tex
Fixes #636 reported by Michael Macias.
I chose to add "optionally" as IMO it reads better than "zero or more".
=> Clarify CRAM language on empty files (PR #638).

VCFv4.3.tex
The definition of valid characters for ALT IDs is present in both
the metadata section and the data lines sections, and was
different.
metadata section:
> ID values are case sensitive strings and must not contain whitespace or angle brackets.
data section:
> (String; no whitespace, commas, or angle-brackets are permitted in the ID String itself) 
I'm not sure which one is the intended definition (given that this difference has been present since the VCF documents were added to the repo in 2013) , but I guess it was intended to ban commas in the IDs?
**Also**, I haven't included the changes for v4.1 and 4.2 but can do so if you think it's worth to make the retroactive change.
I would like to take the opportunity to humbly ask why the decision was made to put the definition of the same …
=> make definition of valid chars for ALT IDs consistent

VCFv4.3.tex, VCFv4.4.draft.tex
No changes to the text or even to the formatting. Removes a LaTeX warning.
Move `\label` to `\endlastfoot` so it is emitted once even for a multi-page table. Fixes #605.
We don't currently use `\listoftables`; nonetheless use `\caption[]` and `\caption[TOC_text]{…}` to emit only one contents entry per table.
=> Tidy up longtable captions and labels [minor]

htsget.md
Add links to previous formal htsget specification releases, using links to the slightly inferiorly rendered GitHub repository view. Fixes #585.
Also add repository URL and version information as a document subtitle, similarly to the title page information on the PDF specifications.
Rendered version can be previewed at http://jmarshall.github.io/hts-specs/htsget.html
=> Add commit hash and links to previous htsget specifications

VCFv4.1.tex, VCFv4.2.tex
Dear hts-spec team. Hello.
I was reading hts-spec's `5.4 Specifying complex rearrangements with breakends` today, and I am reporting that I have found what appears to be a minor typo.
Have a nice day.
=> Fix minor typo in VCF specs

CRAMv3.tex
The reference sequence ID, alignment start and alignment span have no
meaning in the initial CRAM header container.  We make this explicit.
Fixes #645
=> Tighten CRAM container language.

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex, VCFv4.4.draft.tex
Very small PR to clarify that the MD5 for contigs are calculated from the sequence and not the whole file
This is not addressing #551 but should clarify what is already stated
=> Clarify the the source of the contig in VCF

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex, test/vcf/4.1/failed/failed_meta_pedigreedb_002.vcf, test/vcf/4.1/passed/complexfile_passed_000.vcf, test/vcf/4.1/passed/passed_meta_pedigreedb.vcf, test/vcf/4.2/failed/failed_meta_pedigreedb_002.vcf, test/vcf/4.2/passed/complexfile_passed_000.vcf, test/vcf/4.2/passed/passed_meta_pedigreedb.vcf, test/vcf/4.3/failed/failed_meta_pedigreedb_002.vcf, test/vcf/4.3/passed/complexfile_passed_000.vcf, test/vcf/4.3/passed/passed_meta_pedigreedb.vcf
PR #88 introduced the term “**structured** meta-information line”, but was unclear about the relationship between those and other meta-information lines, and §1.4 remains unclear overall — see e.g. #608.
This PR introduces the term “**unstructured** meta-information line” (an alternative might be “**simple** meta-information line”), and rewords this section so it describes the two flavours of meta-information line clearly.
This PR does not attempt to tighten up the syntax around what should be quoted etc as advocated for in #608. OTOH it does newly specify that:
* unstructured values must be non-empty (as is claimed as a rule by some of the test files)
* unstructured values must not start with `<` (so that structured/unstructured are easily distinguished; this is already de facto enforced …
=> Clarify description of structured vs unstructured meta-information lines

.circleci/README.md, .github/actions/texlive/action.yaml, .github/workflows/README.md, .github/workflows/pr-comment.yaml, .github/workflows/pr-pdfs-close.yaml, .github/workflows/pr-pdfs.yaml
Use GitHub's recommended two-part approach[^1][^2] to separate building the PDFs (which runs in the PR branch's context and has only a read-only GH token) from commenting on the PR (which runs on the master branch and has write access to the repository).
[^1]: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
[^2]: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
See jmarshall/hts-specs#2 and jmarshall/hts-specs#3 for examples of this running in that repository.
=> Build PDFs and comment on PRs using GitHub Actions

VCFv4.1.tex, VCFv4.3.tex, VCFv4.4.draft.tex
Genotype fields in the VCF example don't match the encoding equivalent. Typo was fixed in 2015 for 4.2 only (commit: https://github.com/samtools/hts-specs/commit/b6abaee0bab868437df7e4b78900d9aa18a90e3d), so this PR makes the same changes for 4.1, 4.3, and 4.4. 
Note that this only updates the .tex, not the PDFs.
=> fixed typo in Genotype encoding example

VCFv4.3.tex
Original text:
> The structured `contig` field must include the ID attribute and can includes additional optional attributes with
Proposed text:
> The structured `contig` field must include the ID attribute and can include additional optional attributes with
=> Fixed typo in VCFv4.3 Spec

VCFv4.4.draft.tex
I thought I'd have a quick look through the VCF4.4 specification before it goes live.  I've put some suggested changes here.  I've put each suggestion in its own commit, which may (or may not...) make it easier to drop the ones you don't like.  They can all be squashed together when merging.
Another thing I noticed, but haven't fixed here is in the "genotype fields" `PSO` section, where the `PSL` data looks inconsistent with the `GT` fields:
```
#CHROM POS REF ALT INFO FORMAT SAMPLE1
chr1	10	T	<DUP>	SVCLAIM=DJ	GT:PSL:PSO	/0/0|1:.,.,chr1*10*1:.,.,3
chr1	20	A	G	.	GT:PSL:PSO	/0/0|0|1:.,chr1*10*1:.,.,4,1
chr1	30	G	T	.	GT:PSL:PSO	/0/0|0|1:.,chr1*10*1:.,.,2,5
```
Shouldn't there be two MISSING and two present `PSL`s on the last two lines (or a different `GT`?)
Also, I see the `PSL` section …
=> Vcf4.4 proofreading

test/sam/passed/aux.pass-H.sam
The spec requires uppercase only, and we already have a failed sam/failed/aux.fail-H2.sam as a validation that lowercase is incorrect.
Fixes #693
=> Remove use of lowercase hex in SAM aux "H" tag in test data

CRAMv3.tex
In theory a zero length block should be RAW format, because all compression codecs add at least 1 byte of meta-data and an empty block of data (post decompression) will never be zero bytes once compressed.
However htsjdk has always been producing blocks claiming to be RANS compressed and zero bytes long.  This is an illegal RANS stream.
For efficiency reasons, if the uncompressed data is labelled as zero bytes it already knows it'll decode to nothing so it doesn't bother trying (treating it as empty & RAW).  So it didn't spot the broken files.
Given the sheer amount of invalid data out there, we instead amend the specification to bless the problem-avoidance strategy used by htslib.
Fixes #680
=> CRAM: document process for handling empty blocks.

CRAMv3.tex
It still isn't sufficient to adequately explain how templates with
three reads may be encoded.  We probably need diagrams for that.
However it corrects the issue of being out by one in the distance
encoding between mate pairs.
Partially addresses #458
=> CRAM: Improve NF (next frag) description.

crypt4gh.tex
=> Fix typos (Crypt4GH)

SAMv1.tex
Draft text clarifying the paragraph around file encoding, locales, and regular expressions.
Addresses #664.
I would like to spell it out in the first sentence a bit more but haven't come up with a great wording yet; something like
> SAM files are encoded in UTF-8 using mainly ASCII characters only.
=> Clarify SAM file encoding (mostly ASCII, some UTF-8 parts)

CRAMv3.tex
This also clarifies that an embedded reference is not required to exactly match any known external references nor the one used to originally align against.
Fixes #357.
Also fixes #453 as the one remaining part left was the interaction of MD/NM and embedded references.
=> Spell out slice md5sums interaction with embedded references

SAMtags.tex, SAMv1.tex
The `=` and `X` CIGAR operations were added to SAM in 07dc1c67a717 in July 2010, which was the initial addition of the TeX specification; they were not present in the previous Pages document. It's so long ago as to be barely relevant now, but it's worth adding them to the history appendix and identifying them as requiring VN:1.3 rather than VN:1.0.
See the comments on [this biostars posting](https://www.biostars.org/p/9577441/) for the motivating context.
In the SAM regexp in §1.4, write the operations in the familiar canonical order (though it doesn't affect the meaning of the regexp). Define `\cigarops{...}` to improve the formatting of lists of CIGAR operations like "M/I/D" by making the slashes non-`\tt`, and also use this in _SAMtags.tex_.
=> Add CIGAR =/X entry to version history appendix

CRAMv3.tex
=> Fix minor typos in the CRAM tag type lists (PR #761)

VCFv4.5.draft.tex
VCF 4.5 Release Candidate 2 changes:
- Added FORMAT Type=M to enable custom/implementation-defined base modification tags
- Added key aliases that correspond to SAM `MM` tag abbreviations
- Added DP* base modification fields
- Added AD* base modification fields
- Note that due to the encoding of M fields, AD is essentially a combined ADF and ADR tag
- (This design does not support reporting both AD and ADF/ADR (AD is inferred when the negative strand information is MISSING. Please comment/raise an issue if this is a concern).
=> VCFv4.5 RC2

CRAMv3.tex
This was added as clarification in #398 after discussion in #396, but this was in error.  In our attempts to clarify and nail down these corner cases, we failed to recall that the SAM header is permitted to be padded out by non-block allocated space.
History on this decision dates back to 2013 and is show in Samtools issue samtools/samtools#1852.
There are good reasons for changing away from the decision of padding via a second block, as changing block sizes can also change block structure size (if we're using a generic shared piece of code, due to ITF8 being a variable length integer), and this in turn makes it cumbersome to handle every possible change in SAM header size.  It is far easier and simpler to just have unallocated space after the block and before the end of the container. …
=> Revert defn of CRAM container size to be sum of block sizes (PR#731)

CRAMv3.tex
This was a trivial negation typo.  Fixes #749.
=> Fix CRAM pseudocode for handling BAM mapped flag (PR #788)

SAMtags.tex
This is used as a sanity check on the validity of the MM and ML tags. It holds the length of SEQ at the time MM and ML were produced and/or updated.  The intention is to provide a mechanism to detect hard-clipping has been performed with a tool that is not MM/ML aware.
Fixes #646
=> Add an MN:i tag (number of SEQ bases at time of modification tag update).

VCFv4.5.tex
Trivial formatting improvement; fixes #793.
=> Set off example tabular environment with the usual spacing [formatting]

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex, VCFv4.4.tex
With the recent [promulgation of VCF v4.5](https://twitter.com/GA4GH/status/1820915065114992984), add “superseded by…” subtitles to the v4.3 and v4.4 specs. Cf PR #542.
Adjust the v4.1 and v4.2 subtitles to account for newer specs. The previous v4.2 noted “[new spec] introduced in October 2015” because the note was added years after the fact; we don't need to emphasis that this time around as we're contemporaneous.
=> Add subtitles noting VCFv4.[1-4].pdf have been superseded by later versions

SAMv1.tex, test/sam/failed/hdr.RG6.sam
This is not changing what is valid / permitted, and indeed this hopefully clarifies it further.  However the practicality of dealing with wide-spread non-compliant data with lowercase PL values is that tools may wish to be lenient and use case-insensitive matching.
Fixes #679
=> SAM: add a sentence on case-insensitivity of RG PL (PR #684)

CRAMcodecs.tex
This includes all visible read name bytes plus 1 termination byte per name (e.g. '\0').
Fixes #802
=> Clarify the name tokeniser uncomp_len calculation (PR #803)

CRAMv3.tex
=> Document CRAM NP and AP (non-delta) as 1-based coordinates.

CRAMv3.tex
This matches io_lib, htslib and htsjdk's implementations, none of which adhered to the documented 1-based coordinates.
Fixes #807
=> Fix CRAM record counter to be 0 based.

CRAMv3.tex
Given it's working in bits, the example is much clearer if we describe the bits instead of hex, especially distinguishing bits set/unset from bits-yet-to-use.
I also reworked the note at the end of the section as it was quite hard to follow.  I gave it real examples of BETA and HUFFMAN to clarify what is meant by the decoder needing to know the number of bits to consume.
Fixes #812.
=> Rework the CRAM bit encoding example and clarify text

SAMv1.tex
This is an extreme edge case likely to never occur, but nevertheless tool implementors still need to know how to handle it.  Given it *may* be QUAL 9 or it *may* be QUAL "unknown", we treat it as always unknown.
Fixes #715
=> Document the ambiguity of 1-base long seq with QUAL *
