VCFv4.3.tex
This section is our opportunity to **specify** `##fileformat`, not just give an example.
=> Be definitive in the ##fileformat section

VCFv4.3.tex
Following the discussion in #104, this PR introduces the changes that have been flagged as "OK" in the Google Docs document.
=> More strict language in the VCF specification

CRAMv3.tex
I guess this is what you intended to be.
=> fix styles

MAINTAINERS.md, _config.yml
Will merge this later today, unless there's any suggestions about form or location.
=> Add PDF generation instructions

VCFv4.3.tex
Summary of changes made to the VCF v4.3 specification document since it was first published.
=> VCF v4.3 changelog

htsget.md
Partial proposal for versioning — other aspects are versioning/magic numbers within the JSON text, to be addressed separately.  See discussion in #207.
=> Proposed Accept/Content-Type header-based versioning

htsget.md
incorporating detailed discussion on #235 and some further annealing by me
cc @bakerdb @tk2 @mgcam @kemp-ggh @jeromekelleher @jmarshall @dkj
=> htsget security section 2nd iteration

VCFv4.3.tex
Replaces broken link https://support.basespace.illumina.com/knowledgebase/articles/147078-gvcf-file with https://help.basespace.illumina.com/articles/descriptive/gvcf-files/
Fixes #225
=> Changed gVCF format broken link

SAMv1.tex
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/samtools/hts-specs/117)
=> Added a new DS attribute for @SQ lines to create a standard for storing descriptions

CRAMv3.tex
=> Expand CRAM index section.

SAMv1.tex
- aligment -> alignment
- setttings -> settings
- sufficent -> sufficient
=> Fix minor typos in SAMv1

MAINTAINERS.md
Removing Matt Laird as a maintainer of refget
=> Matt is no longer a maintainer

CRAMv3.tex
Proposed clarification for section CRAM spec section 7.1. See issue https://github.com/samtools/hts-specs/issues/450.
=> Clarify CRAM section 7.1 BAM header in first container.

MAINTAINERS.md
@jmmut Just to confirm with you, are there any outstanding/closing actions which you planned to do as a VCF maintainer?
And also, could someone please add me to this repository?
=> Transfer VCF maintainership from @jmmut to @tskir

SAMv1.tex
PacBio is "Pacific Biosciences" not "Pacific Biotechnology"
=> Fix PacBio name

CRAMv3.tex
=> Add some CRAM history and acknowledgements

htsget.md, pub/htsget-openapi.yaml
Query parameters are passed as JSON.  It is possible to request
more than one location in the returned data.
Very much a work-in-progress at the moment.  Comments welcome.
=> Add POST method to htsget

VCFv4.1.tex, VCFv4.2.tex, VCFv4.3.tex, VCFv4.4.draft.tex
This is a new PR with my changes on top of @pd3's work in order to address @jmarshall comments. 
I believe I've addressed your direct comments and made it more readable.  I only addressed changes you specifically mentioned.  It seems like there are more issues with the way BCF is described which could also be improved, but I didn't do that as part of this pr. 
I fixed the formatting in some of tables which were previously producing garbled output.
=> Add VCF Header length redux

CRAMv3.tex
Fixes #635, reported by Michael Macias
=> Correct pseudocode for CRAM quality decoding (PR#637)

VCFv4.3.tex, VCFv4.4.draft.tex
I was asked to summarise the changes introduced between 4.3 and 4.4 and though I might as well add it here. 
I also added the change list between 4.1 and 4.2 for completeness
=> VCF4.3 to VCF4.4 change list

VCFv4.4.draft.tex, examples/vcf/sv44.vcf
Incorporating feedback from public comment period
=> Addressing VCF 4.4 feedback

SAMv1.tex
This is a request to add ELEMENT to the controlled vocabulary for the PL header tag
=> Add ELEMENT to PL header tag

SAMv1.tex
....to the list of allowed values for the PL tag.
=> adding ultima genomics platform

SAMv1.tex
This request is to add Singular Genomics `SINGULAR` to list of platforms
=> add SINGULAR to platform tags

CRAMv3.tex
Fixes #747
(Also updated the languishing CRAM4 PR with the same changes.)
=> Document CRAM FP is delta-encoded

test/sam/passed/aux.pass-tag.sam
=> Trivial removal of duplicate tag in SAM test data
